### ISSUE TITLE
[Feature] Add LogsBucket and DemoBucket Logical IDs to Outputs

### ISSUE THREAD

**Issue by rezabekf** [awslabs/live-stream-on-aws#12]
**Is your feature request related to a problem? Please describe.**
Outputting LogsBucket and DemoBucket Logical IDs will allow to extend and implement analytics solution https://github.com/aws-samples/amazon-cloudfront-access-logs-queries

**Describe the feature you'd like**
In the Outputs section of the `live-streaming-on-aws.yaml`, output `LogsBucket` and `DemoBucket` Logical IDs

```
Outputs:
  LogsBucket:
    Description: Logs bucket
    Value: !Ref LogsBucket
  
  DemoBucket:
    Description: Demo bucket
    Value: !Ref DemoBucket
```
Thanks,
Franco
