### ISSUE TITLE
Adding support for input creation in a VPC

### ISSUE THREAD

**Issue by mehdi-abbad** [awslabs/live-stream-on-aws#9]
I'm trying to figure out a way of using this in the context of a VPC.
I modified the code to be able to specify a vpc and subnets as required by the SDK documentation, but at creation, the lambda function fails with the following message:
```
FAILED:: BadRequestException: The Arn of an IAM role that allows MediaLive to manage network interfaces in your VPC is required to create a VPC input.
```
I've added this to the CustomResourceRole :
```
  -
    Effect: Allow
    Action:
      - ec2:*
    Resource: 
       - !Join ["", ["arn:aws:ec2:", Ref: "AWS::Region", ":", Ref: "AWS::AccountId", ":*"]] 
```
But it doesn't seem to work.
Any ideas ?
